name: Build .NET

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build .NET
        run: sudo --preserve-env bash build.sh